### ISSUE TITLE
Desk height NaN - card buttons don't work

### ISSUE THREAD

**Issue by simbesh** [IhorSyerkov/linak-desk-card#11]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
1.0.2
**Last working release (if known):**
?
**Browser and Operating System:**
Chrome

**Description of problem:**

The configuration seems ok, follow all instructions and copy/pasted config.

Desk Height is showing NaN, this is also causing the buttons to not work.
desk height looks correct in `sensor.desk_height`

![image](https://user-images.githubusercontent.com/17171925/112912704-84150480-913b-11eb-8e93-705af5082893.png)
![image](https://user-images.githubusercontent.com/17171925/112912738-98590180-913b-11eb-8956-35ee213b61b0.png)
![image](https://user-images.githubusercontent.com/17171925/112912855-eb32b900-913b-11eb-83d5-eb3f0f3ab021.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
HACS version 1.11.3
HA version core-2021.3.4

**Comment by Nicras** [comment]
I have the same problem and as of now we got v2.0.1 of j5liens desk-controller for esphome.
Could you please update this lovely card to work again? Would be really great.

Cheers

**Comment by Nicras** [comment]
no reaction? Is this repo dead?

**Comment by IhorSyerkov** [comment]
Hi @Nicras. Try to use latest 1.1.0 version. And recofigure the card min_height and max_height fields are required now.
Sorry about late response. I do not have alot of free time for my pet projects :)

**Comment by simbesh** [comment]
@IhorSyerkov  Thanks mine is working now :)
