### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Nicras** [IhorSyerkov/linak-desk-card#13]
Hi,
I just want to provide you with a german translation:

{
  "common": {
    "version": "Version",
    "name":"Linak Desk Card",
    "description": "Kontrolliere die Tischhöhe mit dieser Karte",
    "invalid_configuration": "Fehlerhafte Konfiguration",
    "desk_and_height_required": "Tisch- und Höhensensor sind erforderlich",
    "min_and_max_height_required": "`min_height` und `max_height` Einstellungen sind erforderlich"
  },
  "editor": {
    "name": "Name (Optional)",
    "desk":"Tisch Entität (Erforderlich)",
    "height_sensor":"Height Sensor (Erforderlich)",
    "connection_sensor":"Verbindungs-Sensor (Erforderlich)",
    "moving_sensor":"Höhen-Sensor (Erforderlich)",
    "min_height":"Min Höhe (Erforderlich)",
    "max_height":"Max Höhe (Erforderlich)",
    "presets":"Voreinstellungen"
  },
  "status": {
    "connected": "Verbunden",
    "disconnected": "Getrennt"
  }
}

**Comment by IhorSyerkov** [comment]
Tanks @Nicras. WIll add german version

**Comment by IhorSyerkov** [comment]
@Nicras German translation added in v1.2.0
